spring:
  application:
    name: feign-login
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: ${port:8763}
feign:
  hystrix:
    enabled: true
zuul:
  routes:
    api-log:
      path: /api-log/**
      serviceId: privoducerlog


